Repository MyPureCloud/terraform-provider-genesyscloud, pull requests merged in 2021-10, with the labels that each got.

#94 Adding trunks
  docs/resources/telephony_providers_edges_trunk.md
  examples/resources/genesyscloud_telephony_providers_edges_trunk/apis.md
  examples/resources/genesyscloud_telephony_providers_edges_trunk/resource.tf
  genesyscloud/provider.go
  genesyscloud/resource_exporter.go
  genesyscloud/resource_genesyscloud_telephony_providers_edges_edge_group.go
  genesyscloud/resource_genesyscloud_telephony_providers_edges_edge_group_test.go
  genesyscloud/resource_genesyscloud_telephony_providers_edges_trunk.go
  genesyscloud/resource_genesyscloud_telephony_providers_edges_trunk_test.go
  genesyscloud/resource_genesyscloud_telephony_providers_edges_trunkbasesettings.go
  genesyscloud/util_retries.go
Labels: feature

#95 Adding sites resource and data source
  docs/data-sources/telephony_providers_edges_site.md
  docs/resources/telephony_providers_edges_site.md
  examples/data-sources/genesyscloud_telephony_providers_edges_site/data-source.tf
  examples/resources/genesyscloud_telephony_providers_edges_site/apis.md
  examples/resources/genesyscloud_telephony_providers_edges_site/resource.tf
  genesyscloud/data_source_genesyscloud_telephony_providers_edges_site.go
  genesyscloud/data_source_genesyscloud_telephony_providers_edges_site_test.go
  genesyscloud/provider.go
  genesyscloud/resource_exporter.go
  genesyscloud/resource_genesyscloud_location.go
  genesyscloud/resource_genesyscloud_location_test.go
  genesyscloud/resource_genesyscloud_telephony_providers_edges_phone.go
  genesyscloud/resource_genesyscloud_telephony_providers_edges_site.go
  genesyscloud/resource_genesyscloud_telephony_providers_edges_site_test.go
Labels: feature

#113 Adding optional web_rtc_user_id to phone docs
  docs/resources/telephony_providers_edges_phone.md
Labels: doc

#120 CXCODE-52 phone data source
  docs/data-sources/telephony_providers_edges_phone.md
  examples/data-sources/genesyscloud_telephony_providers_edges_phone/data-source.tf
  genesyscloud/data_source_genesyscloud_telephony_providers_edges_phone.go
  genesyscloud/data_source_genesyscloud_telephony_providers_edges_phone_test.go
  genesyscloud/provider.go
Labels: feature

#124 CXCODE-51 trunk data source
  docs/data-sources/telephony_providers_edges_trunk.md
  docs/resources/telephony_providers_edges_trunk.md
  examples/data-sources/genesyscloud_telephony_providers_edges_trunk/data-source.tf
  genesyscloud/data_source_genesyscloud_telephony_providers_edges_trunk.go
  genesyscloud/data_source_genesyscloud_telephony_providers_edges_trunk_test.go
  genesyscloud/provider.go
  genesyscloud/resource_genesyscloud_telephony_providers_edges_trunk.go
Labels: feature

#122 CXCODE-38 Architect User Prompt Resource
  docs/data-sources/architect_user_prompt.md
  docs/resources/architect_user_prompt.md
  examples/data-sources/genesyscloud_architect_user_prompt/data-source.tf
  examples/resources/genesyscloud_architect_user_prompt/apis.md
  examples/resources/genesyscloud_architect_user_prompt/resource.tf
  genesyscloud/data_source_genesyscloud_architect_user_prompt.go
  genesyscloud/data_source_genesyscloud_architect_user_prompt_test.go
  genesyscloud/provider.go
  genesyscloud/resource_exporter.go
  genesyscloud/resource_genesyscloud_architect_user_prompt.go
  genesyscloud/resource_genesyscloud_architect_user_prompt_test.go
  genesyscloud/test-prompt-01.wav
  genesyscloud/test-prompt-02.wav
Labels: feature

#148 CXCODE-66 wrap-up code data source
  docs/data-sources/routing_wrapupcode.md
  examples/data-sources/genesyscloud_routing_wrapupcode/data-source.tf
  genesyscloud/data_source_genesyscloud_routing_wrapupcode.go
  genesyscloud/data_source_genesyscloud_routing_wrapupcode_test.go
  genesyscloud/provider.go
Labels: feature

#153 Fixing usage of ForceNew in the site resource
  genesyscloud/resource_genesyscloud_telephony_providers_edges_site.go
  genesyscloud/resource_genesyscloud_telephony_providers_edges_site_test.go
Labels: bug
