Repository MyPureCloud/terraform-provider-genesyscloud, pull requests merged in 2023-02, with the labels that each got.

#431 [DEVENGAGE-983] Exporting user prompt audio
  genesyscloud/resource_exporter.go
  genesyscloud/resource_exporter_custom.go
  genesyscloud/resource_genesyscloud_architect_user_prompt.go
  genesyscloud/resource_genesyscloud_tf_export.go
  genesyscloud/resource_genesyscloud_tf_export_test.go
Labels: feature

#430 DEVENGAGE-1445 Responsemanagement responses
  docs/data-sources/responsemanagement_response.md
  docs/resources/responsemanagement_response.md
  examples/data-sources/genesyscloud_responsemanagement_response/data-source.tf
  examples/resources/genesyscloud_responsemanagement_response/apis.md
  examples/resources/genesyscloud_responsemanagement_response/resource.tf
  genesyscloud/data_source_genesyscloud_responsemanagement_response.go
  genesyscloud/data_source_genesyscloud_responsemanagement_response_test.go
  genesyscloud/provider.go
  genesyscloud/resource_exporter.go
  genesyscloud/resource_genesyscloud_responsemanagement_response.go
  genesyscloud/resource_genesyscloud_responsemanagement_response_test.go
Labels: feature

#444 [no jira] Adding all required fields to action map resource example
  docs/resources/journey_action_map.md
  examples/resources/genesyscloud_journey_action_map/resource.tf
Labels: doc

#443 DEVENGAGE-1638: Fixed bug in audio prompt custom export function
  genesyscloud/resource_genesyscloud_architect_user_prompt.go
  genesyscloud/resource_genesyscloud_tf_export_test.go
Labels: bug

#450 Feat/vip routing queue settings
  docs/resources/routing_queue.md
  genesyscloud/resource_genesyscloud_routing_queue.go
  genesyscloud/resource_genesyscloud_routing_queue_test.go
Labels: feature

#449 Feat/devengage 1630 add cobrowse to webdeployment config
  docs/resources/webdeployments_configuration.md
  examples/resources/genesyscloud_webdeployments_configuration/resource.tf
  genesyscloud/resource_genesyscloud_webdeployments_configuration.go
  genesyscloud/resource_genesyscloud_webdeployments_configuration_test.go
Labels: feature
