Repository MyPureCloud/terraform-provider-genesyscloud, pull requests merged in 2024-05, with the labels that each got.

#1004 DEVTOOLING-352 - provider oauth credential rate limit exceeded
  genesyscloud/provider/provider.go
Labels: bug

#1020 bug/devtooling 560 - CX as Code crash when creating phones
  genesyscloud/station/data_source_genesyscloud_station_test.go
  genesyscloud/telephony_providers_edges_phone/data_source_genesyscloud_telephony_providers_edges_phone_test.go
  genesyscloud/telephony_providers_edges_phone/resource_genesyscloud_telephony_providers_edges_phone.go
  genesyscloud/telephony_providers_edges_phone/resource_genesyscloud_telephony_providers_edges_phone_test.go
  genesyscloud/telephony_providers_edges_phone/resource_genesyscloud_telephony_providers_edges_phone_utils.go
Labels: bug

#1014 Bug/devtooling 444: Custom resolver function for outbound campaign script_id
  genesyscloud/outbound_campaign/data_source_genesyscloud_outbound_campaign_test.go
  genesyscloud/outbound_campaign/genesyscloud_outbound_campaign_proxy.go
  genesyscloud/outbound_campaign/resource_genesyscloud_outbound_campaign.go
  genesyscloud/outbound_campaign/resource_genesyscloud_outbound_campaign_schema.go
  genesyscloud/outbound_campaign/resource_genesyscloud_outbound_campaign_test.go
  genesyscloud/outbound_campaign/resource_genesyscloud_outbound_campaign_utils.go
  genesyscloud/resource_cache/inmemory_cache.go
  genesyscloud/resource_cache/resource_cache.go
  genesyscloud/resource_exporter/resource_exporter.go
  genesyscloud/resource_exporter/resource_exporter_custom.go
  genesyscloud/resource_exporter/resource_exporter_unit_test.go
  genesyscloud/scripts/data_source_genesyscloud_script_test.go
  genesyscloud/scripts/genesyscloud_scripts_proxy.go
  genesyscloud/scripts/resource_genesyscloud_script.go
  genesyscloud/scripts/resource_genesyscloud_script_test.go
  genesyscloud/tfexporter/genesyscloud_resource_exporter.go
  genesyscloud/tfexporter/genesyscloud_resource_exporter_test.go
  genesyscloud/tfexporter/resource_genesyscloud_tf_export_test.go
  genesyscloud/tfexporter/tf_exporter_resource_test.go
  genesyscloud/util/constants/constants.go
Labels: bug

#999 Devtooling-162: Refactored idp salesforce
  genesyscloud/idp_salesforce/genesyscloud_idp_salesforce_init_test.go
  genesyscloud/idp_salesforce/genesyscloud_idp_salesforce_proxy.go
  genesyscloud/idp_salesforce/resource_genesyscloud_idp_salesforce.go
  genesyscloud/idp_salesforce/resource_genesyscloud_idp_salesforce_schema.go
  genesyscloud/idp_salesforce/resource_genesyscloud_idp_salesforce_test.go
  genesyscloud/resource_genesyscloud_idp_salesforce.go
  genesyscloud/resource_genesyscloud_init.go
  genesyscloud/resource_genesyscloud_init_test.go
  genesyscloud/tfexporter/tf_exporter_resource_test.go
  main.go
Labels: refactor

#1029 bug/DEVTOOLING-557 - Changed Build Function Call to fix type difference
  genesyscloud/resource_genesyscloud_journey_segment.go
Labels: bug

#1030 No-Jira - fixing test for published attribute
  genesyscloud/resource_genesyscloud_quality_forms_evaluation.go
Labels: bug

#1028 Fix routing queue
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_test.go
Labels: bug

#1027 Pre-verify if the tfState is in sync with the exporter
  genesyscloud/tfexporter/genesyscloud_resource_exporter.go
  genesyscloud/tfexporter/json_exporter.go
  genesyscloud/tfexporter/tfstate_export_reader.go
  genesyscloud/tfexporter/tfstate_exporter.go
  genesyscloud/util/feature_toggles/state_comparison.go
  genesyscloud/util/files/util_files.go
Labels: feature

#1035 Feature/devtooling 589 1
  docs/guides/export.md
  templates/guides/export.md.tmpl
Labels: feature

#1039 Bug/devtooling 597 - Routing email route test failing
  genesyscloud/routing_email_route/resource_genesyscloud_routing_email_route.go
  genesyscloud/routing_email_route/resource_genesyscloud_routing_email_route_test.go
  genesyscloud/routing_email_route/resource_genesyscloud_routing_email_route_utils.go
Labels: bug

#1041 NO-JIRA: Fixing nil pointer in consistency checker
  genesyscloud/consistency_checker/consistency_checker.go
  genesyscloud/outbound_settings/resource_genesyscloud_outbound_settings.go
  genesyscloud/outbound_settings/resource_genesyscloud_outbound_settings_utils.go
Labels: hotfix

#1045 DEVTOOLING-595: Integration Nil pointer exception
  genesyscloud/integration/resource_genesyscloud_integration.go
Labels: hotfix

#1038 bug/DEVTOOLING-436 - Added cleanup function for webdeployments resources
  genesyscloud/webdeployments_configuration/data_source_genesyscloud_webdeployments_configuration.go
  genesyscloud/webdeployments_configuration/data_source_genesyscloud_webdeployments_configuration_test.go
  genesyscloud/webdeployments_configuration/resource_genesyscloud_webdeployments_configuration.go
  genesyscloud/webdeployments_configuration/resource_genesyscloud_webdeployments_configuration_test.go
  genesyscloud/webdeployments_configuration/utils/resource_genesyscloud_webdeployments_configuration_utils.go
  genesyscloud/webdeployments_deployment/data_source_genesyscloud_webdeployments_deployment_test.go
  genesyscloud/webdeployments_deployment/resource_genesyscloud_webdeployments_deployment.go
  genesyscloud/webdeployments_deployment/resource_genesyscloud_webdeployments_deployment_test.go
Labels: bug

#1049 Bug/devtooling 354
  genesyscloud/tfexporter/resource_genesyscloud_tf_export.go
Labels: bug

#1050 DEVTOOLING-449: Logging error in queue create/update instead of failing
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue.go
Labels: bug

#1052 Add extra check for dependency resolution
  genesyscloud/tfexporter/genesyscloud_resource_exporter.go
  genesyscloud/tfexporter/genesyscloud_resource_exporter_test.go
Labels: feature

#1055 DEVTOOLING-592: Changed team members logic
  docs/resources/team.md
  genesyscloud/group/resource_genesyscloud_group.go
  genesyscloud/team/resource_genesyscloud_team.go
  genesyscloud/team/resource_genesyscloud_team_schema.go
  genesyscloud/team/resource_genesyscloud_team_test.go
  genesyscloud/team/resource_genesyscloud_team_utils.go
Labels: bug

#1048 Feat/devtooling-477: Site Outbound Routes Resource
  docs/resources/telephony_providers_edges_site.md
  docs/resources/telephony_providers_edges_site_outbound_route.md
  examples/resources/genesyscloud_telephony_providers_edges_site_outbound_route/apis.md
  examples/resources/genesyscloud_telephony_providers_edges_site_outbound_route/resource.tf
  genesyscloud/telephony_providers_edges_site/data_source_genesyscloud_telephony_providers_edges_site.go
  genesyscloud/telephony_providers_edges_site/genesyscloud_telephony_providers_edges_site_proxy.go
  genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site.go
  genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site_schema.go
  genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site_test.go
  genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site_utils.go
  genesyscloud/telephony_providers_edges_site_outbound_route/genesyscloud_telephony_providers_edges_site_outbound_route_init_test.go
  genesyscloud/telephony_providers_edges_site_outbound_route/genesyscloud_telephony_providers_edges_site_outbound_route_proxy.go
  genesyscloud/telephony_providers_edges_site_outbound_route/resource_genesyscloud_telephony_providers_edges_site_outbound_route.go
  genesyscloud/telephony_providers_edges_site_outbound_route/resource_genesyscloud_telephony_providers_edges_site_outbound_route_schema.go
  genesyscloud/telephony_providers_edges_site_outbound_route/resource_genesyscloud_telephony_providers_edges_site_outbound_route_test.go
  genesyscloud/telephony_providers_edges_site_outbound_route/resource_genesyscloud_telephony_providers_edges_site_outbound_route_utils.go
  genesyscloud/tfexporter/tf_exporter_resource_test.go
  genesyscloud/util/feature_toggles/outbound_routes.go
  main.go
Labels: feature
