Repository MyPureCloud/terraform-provider-genesyscloud, pull requests merged in 2024-12, with the labels that each got.

#1400 feature/DEVTOOLING-163
  genesyscloud/data_source_genesyscloud_journey_action_template_test.go
  genesyscloud/journey_action_map/data_source_genesyscloud_journey_action_map.go
  genesyscloud/journey_action_map/data_source_genesyscloud_journey_action_map_test.go
  genesyscloud/journey_action_map/genesyscloud_journey_action_map_init_test.go
  genesyscloud/journey_action_map/genesyscloud_journey_action_map_proxy.go
  genesyscloud/journey_action_map/resource_genesyscloud_journey_action_map.go
  genesyscloud/journey_action_map/resource_genesyscloud_journey_action_map_schema.go
  genesyscloud/journey_action_map/resource_genesyscloud_journey_action_map_test.go
  genesyscloud/journey_action_map/resource_genesyscloud_journey_action_map_utils.go
  genesyscloud/resource_genesyscloud_init.go
  genesyscloud/resource_genesyscloud_init_test.go
  genesyscloud/resource_genesyscloud_journey_action_map_test.go
  genesyscloud/tfexporter/tf_exporter_resource_test.go
  genesyscloud/util/testrunner/testrunner.go
  main.go
Labels: feature

#1408 Feature/devtooling 165
  genesyscloud/journey_action_template/data_source_genesyscloud_journey_action_template.go
  genesyscloud/journey_action_template/data_source_genesyscloud_journey_action_template_test.go
  genesyscloud/journey_action_template/genesyscloud_journey_action_template_init_test.go
  genesyscloud/journey_action_template/genesyscloud_journey_action_template_proxy.go
  genesyscloud/journey_action_template/resource_genesyscloud_journey_action_template.go
  genesyscloud/journey_action_template/resource_genesyscloud_journey_action_template_schema.go
  genesyscloud/journey_action_template/resource_genesyscloud_journey_action_template_test.go
  genesyscloud/journey_action_template/resource_genesyscloud_journey_action_template_utils.go
  genesyscloud/resource_genesyscloud_init.go
  genesyscloud/resource_genesyscloud_init_test.go
  genesyscloud/tfexporter/tf_exporter_resource_test.go
  genesyscloud/util/testrunner/testrunner.go
Labels: feature

#1412 Fix testcase
  genesyscloud/routing_skill_group/resource_genesyscloud_routing_skill_group_test.go
Labels: feature

#1423 DEVTOOLING-908: Avoiding nil pointer dereference in exporter
  genesyscloud/tfexporter/genesyscloud_resource_exporter.go
Labels: bug

#1427 tested with smtp
  genesyscloud/routing_email_domain/resource_genesyscloud_routing_email_domain.go
Labels: bug

#1422 Enhance replaceDatasource setup
  genesyscloud/integration/resource_genesyscloud_integration_schema.go
  genesyscloud/resource_exporter/resource_exporter.go
  genesyscloud/resource_exporter/resource_name_sanitizer.go
  genesyscloud/tfexporter/genesyscloud_resource_exporter.go
  genesyscloud/tfexporter/genesyscloud_resource_exporter_test.go
Labels: bug

#1405 OBR-135 Add business categories to wrap up code mappings
  genesyscloud/outbound_wrapupcode_mappings/geneysyscloud_wrapupcode_mappings_schema.go
  genesyscloud/outbound_wrapupcode_mappings/resource_genesyscloud_outbound_wrapupcode_mappings_test.go
Labels: feature

#1424 Feature/devtooling 963
  docs/resources/routing_queue.md
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_schema.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_unit_test.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_utils.go
Labels: feature

#1426 Fix DEVTOOLING-936 - Allow updates to default outbound routes
  genesyscloud/telephony_providers_edges_site_outbound_route/data_source_genesyscloud_telephony_providers_edges_site_outbound_route.go
  genesyscloud/telephony_providers_edges_site_outbound_route/data_source_genesyscloud_telephony_providers_edges_site_outbound_route_test.go
  genesyscloud/telephony_providers_edges_site_outbound_route/genesyscloud_telephony_providers_edges_site_outbound_route_proxy.go
  genesyscloud/telephony_providers_edges_site_outbound_route/resource_genesyscloud_telephony_providers_edges_site_outbound_route.go
  genesyscloud/telephony_providers_edges_site_outbound_route/resource_genesyscloud_telephony_providers_edges_site_outbound_route_test.go
  genesyscloud/util/testrunner/testrunner.go
Labels: fix

#1429 DEVTOOLING-852 added logs
  genesyscloud/integration/resource_genesyscloud_integration.go
  genesyscloud/integration/resource_genesyscloud_integration_utils.go
  genesyscloud/integration_credential/resource_genesyscloud_integration_credential.go
  genesyscloud/util/util_strings.go
Labels: bug

#1435 return nil on empty response
  docs/resources/routing_queue.md
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_schema.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_utils.go
Labels: feature

#1431 Update outbound campaign
  docs/resources/outbound_campaign.md
  genesyscloud/outbound_campaign/resource_genesyscloud_outbound_campaign.go
  genesyscloud/outbound_campaign/resource_genesyscloud_outbound_campaign_schema.go
  genesyscloud/outbound_campaign/resource_genesyscloud_outbound_campaign_test.go
  genesyscloud/outbound_campaign/resource_genesyscloud_outbound_campaign_utils.go
Labels: bug

#1428 Fixes DEVTOOLING-981
  genesyscloud/architect_grammar_language/genesyscloud_architect_grammar_language_proxy.go
  genesyscloud/architect_grammar_language/resource_genesyscloud_architect_grammar_language.go
  genesyscloud/architect_grammar_language/resource_genesyscloud_architect_grammar_language_test.go
  genesyscloud/architect_grammar_language/resource_genesyscloud_architect_grammar_language_utils.go
  genesyscloud/architect_ivr/resource_genesyscloud_architect_ivr.go
  genesyscloud/integration_credential/resource_genesyscloud_integration_credential.go
  genesyscloud/knowledge/resource_genesyscloud_knowledge_document_variation.go
  genesyscloud/knowledge_category/resource_genesyscloud_knowledge_category.go
  genesyscloud/knowledge_document/resource_genesyscloud_knowledge_document.go
  genesyscloud/knowledge_label/resource_genesyscloud_knowledge_label.go
  genesyscloud/location/resource_genesyscloud_location.go
  genesyscloud/outbound_contact_list_contact/genesyscloud_outbound_contact_list_contact_proxy.go
  genesyscloud/outbound_contact_list_contact/resource_genesyscloud_outbound_contact_list_contact.go
  genesyscloud/outbound_contact_list_contact/resource_genesyscloud_outbound_contact_list_contact_utils.go
  genesyscloud/task_management_worktype_status/resource_genesyscloud_task_management_worktype_status.go
  genesyscloud/telephony_providers_edges_site_outbound_route/resource_genesyscloud_telephony_providers_edges_site_outbound_route.go
Labels: fix

#1420 Fix for DEVTOOLING-967
  genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site_schema.go
  genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site_utils.go
  genesyscloud/util/lists/util_lists.go
Labels: fix
