Repository MyPureCloud/terraform-provider-genesyscloud, pull requests merged in 2024-06, with the labels that each got.

#1063 DEVTOOLING-603: Media recording poilicies missing from export
  docs/resources/recording_media_retention_policy.md
  examples/resources/genesyscloud_recording_media_retention_policy/apis.md
  genesyscloud/recording_media_retention_policy/genesyscloud_recording_media_retention_policy_proxy.go
Labels: bug

#1070 bug/DEVTOOLING-555: Journey Tests Failing
  docs/resources/journey_segment.md
  genesyscloud/data_source_genesyscloud_journey_action_map_test.go
  genesyscloud/data_source_genesyscloud_journey_segment_test.go
  genesyscloud/resource_genesyscloud_init_test.go
  genesyscloud/resource_genesyscloud_journey_action_map_test.go
  genesyscloud/resource_genesyscloud_journey_segment.go
  genesyscloud/resource_genesyscloud_journey_segment_test.go
  test/data/data_source/genesyscloud_journey_action_map/find_by_name/01_find_by_name.tf
  test/data/data_source/genesyscloud_journey_segment/find_by_name/01_find_by_name.tf
  test/data/resource/genesyscloud_journey_action_map/action_media_types/01_create_web_messaging_offer_without_config.tf
  test/data/resource/genesyscloud_journey_action_map/action_media_types/02_update_web_messaging_offer_with_config.tf
  test/data/resource/genesyscloud_journey_action_map/action_media_types/03_update_web_messaging_offer_remove_config.tf
  test/data/resource/genesyscloud_journey_action_map/action_media_types/04_update_content_offer.tf.SKIP
  test/data/resource/genesyscloud_journey_action_map/action_media_types/05_update_architect_flow_without_mapping.tf
  test/data/resource/genesyscloud_journey_action_map/action_media_types/06_update_architect_flow_with_mapping.tf
  test/data/resource/genesyscloud_journey_action_map/action_media_types/07_update_open_action.tf.SKIP
  test/data/resource/genesyscloud_journey_action_map/basic_optional_attributes/01_create.tf
  test/data/resource/genesyscloud_journey_action_map/basic_optional_attributes/02_update_all_optional_changed.tf
  test/data/resource/genesyscloud_journey_action_map/basic_optional_attributes/03_update_remove_trigger_with_outcome_probability_conditions.tf
  test/data/resource/genesyscloud_journey_action_map/basic_optional_attributes/04_update_remove_page_url_conditions.tf
  test/data/resource/genesyscloud_journey_action_map/basic_optional_attributes/05_update_remove_ignore_frequency_cap.tf
  test/data/resource/genesyscloud_journey_action_map/basic_optional_attributes/06_update_remove_end_date.tf
  test/data/resource/genesyscloud_journey_action_map/basic_required_attributes/01_create.tf
  test/data/resource/genesyscloud_journey_action_map/basic_required_attributes/02_update.tf
  test/data/resource/genesyscloud_journey_action_map/schedule_groups/01_create_without_schedule_groups.tf
  test/data/resource/genesyscloud_journey_action_map/schedule_groups/02_update_with_schedule_groups.tf
  test/data/resource/genesyscloud_journey_action_map/schedule_groups/03_update_with_emergency_schedule_group.tf
  test/data/resource/genesyscloud_journey_action_map/schedule_groups/04_update_remove_emergency_schedule_group.tf
  test/data/resource/genesyscloud_journey_action_map/schedule_groups/05_update_remove_schedule_groups.tf
  test/data/resource/genesyscloud_journey_action_map/schedule_groups/06_cleanup_remove_schedule_groups.tf
  test/data/resource/genesyscloud_journey_segment/basic_customer_attributes/01_create_customer_scope.tf
  test/data/resource/genesyscloud_journey_segment/basic_customer_attributes/02_recreate_external_segment_update_name.tf
  test/data/resource/genesyscloud_journey_segment/basic_customer_attributes/03_recreate_external_segment_id_force_new.tf
  test/data/resource/genesyscloud_journey_segment/basic_customer_attributes/04_update_color_change.tf
  test/data/resource/genesyscloud_journey_segment/basic_session_attributes/03_recreate_scope_change_force_new.tf
  test/data/resource/genesyscloud_journey_segment/optional_attributes/01_create.tf
  test/data/resource/genesyscloud_journey_segment/optional_attributes/02_update_all_optional_changed.tf
  test/data/resource/genesyscloud_journey_segment/optional_attributes/03_update_remove_description.tf
  test/data/resource/genesyscloud_journey_segment/optional_attributes/04_update_remove_assignment_expirition_days.tf
Labels: bug

#1071 Bug/devtooling 584
  docs/data-sources/user.md
  genesyscloud/data_source_genesyscloud_user.go
  genesyscloud/data_source_genesyscloud_user_test.go
  genesyscloud/resource_cache/datasource_cache.go
Labels: bug

#1075 fix api call strategy
  genesyscloud/data_source_genesyscloud_routing_skill.go
  genesyscloud/routing_queue/data_source_genesyscloud_routing_queue.go
Labels: feature

#1076 fix update issues for workType
  genesyscloud/task_management_worktype/resource_genesyscloud_task_management_worktype_utils.go
Labels: bug

#1090 Feature/fix unit tests
  genesyscloud/task_management_worktype/resource_genesyscloud_task_management_worktype_unit_test.go
  genesyscloud/task_management_worktype/resource_genesyscloud_task_management_worktype_utils.go
Labels: feature

#1101 fix exporter crash
  genesyscloud/resource_exporter/resource_exporter_custom.go
Labels: bug

#1104 Bug/devtooling 641
  genesyscloud/task_management_worktype/resource_genesyscloud_task_management_worktype_utils.go
Labels: bug

#1084 feat/devtooling 71: Outbound contact list contact resource
  docs/resources/outbound_contact_list_contact.md
  examples/resources/genesyscloud_outbound_contact_list_contact/apis.md
  examples/resources/genesyscloud_outbound_contact_list_contact/resource.tf
  genesyscloud/integration/resource_genesyscloud_integration_test.go
  genesyscloud/integration_action/resource_genesyscloud_integration_action_test.go
  genesyscloud/integration_credential/data_source_genesyscloud_integration_credential_test.go
  genesyscloud/integration_credential/resource_genesyscloud_integration_credential_test.go
  genesyscloud/integration_credential/resource_genesyscloud_integration_credential_utils.go
  genesyscloud/integration_custom_auth_action/data_source_genesyscloud_integration_custom_auth_action_test.go
  genesyscloud/integration_custom_auth_action/resource_genesyscloud_integration_custom_auth_action_test.go
  genesyscloud/outbound_contact_list/resource_genesyscloud_outbound_contactlist.go
  genesyscloud/outbound_contact_list/resource_genesyscloud_outbound_contactlist_test.go
  genesyscloud/outbound_contact_list_contact/genesyscloud_outbound_contact_list_contact_init_test.go
  genesyscloud/outbound_contact_list_contact/genesyscloud_outbound_contact_list_contact_proxy.go
  genesyscloud/outbound_contact_list_contact/resource_genesyscloud_outbound_contact_list_contact.go
  genesyscloud/outbound_contact_list_contact/resource_genesyscloud_outbound_contact_list_contact_schema.go
  genesyscloud/outbound_contact_list_contact/resource_genesyscloud_outbound_contact_list_contact_test.go
  genesyscloud/outbound_contact_list_contact/resource_genesyscloud_outbound_contact_list_contact_utils.go
  genesyscloud/resource_exporter/resource_exporter.go
  genesyscloud/tfexporter/genesyscloud_resource_exporter.go
  genesyscloud/tfexporter/tf_exporter_resource_test.go
  genesyscloud/util/lists/util_lists.go
  genesyscloud/util/resourcedata/resourcedata.go
  genesyscloud/util/test_utils.go
  go.sum
  main.go
Labels: feature

#1108 Bug/devtooling 659
  genesyscloud/telephony_providers_edges_phone/resource_genesyscloud_telephony_providers_edges_phone.go
  genesyscloud/telephony_providers_edges_phone/resource_genesyscloud_telephony_providers_edges_phone_utils.go
Labels: bug

#1089 Feat/devtooling 187 - Refactor routing settings
  docs/data-sources/routing_settings.md
  docs/resources/routing_settings.md
  genesyscloud/data_source_genesyscloud_routing_settings.go
  genesyscloud/data_source_genesyscloud_routing_settings_test.go
  genesyscloud/external_contacts/genesyscloud_externalcontacts_contact_init_test.go
  genesyscloud/resource_genesyscloud_init.go
  genesyscloud/resource_genesyscloud_init_test.go
  genesyscloud/resource_genesyscloud_routing_settings.go
  genesyscloud/routing_settings/genesyscloud_routing_settings_init_test.go
  genesyscloud/routing_settings/genesyscloud_routing_settings_proxy.go
  genesyscloud/routing_settings/resource_genesyscloud_routing_settings.go
  genesyscloud/routing_settings/resource_genesyscloud_routing_settings_schema.go
  genesyscloud/routing_settings/resource_genesyscloud_routing_settings_test.go
  genesyscloud/tfexporter/tf_exporter_resource_test.go
  main.go
Labels: feature

#1107 DEVTOOLING-601: Queue member assignment taking long time
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue.go
Labels: bug

#1114 feat/DEVTOOLING-602 onHoldPrompt attribute
  docs/resources/routing_queue.md
  genesyscloud/routing_queue/genesyscloud_routing_queue_init_test.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_schema.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_test.go
Labels: feature

#1105 refactor/Devtooling-190 [routing_utilization] + Devtooling-400 [routing_utilization_label]
  genesyscloud/data_source_genesyscloud_routing_utilization_label.go
  genesyscloud/resource_genesyscloud_init.go
  genesyscloud/resource_genesyscloud_init_test.go
  genesyscloud/resource_genesyscloud_routing_skill_group.go
  genesyscloud/resource_genesyscloud_routing_skill_group_test.go
  genesyscloud/resource_genesyscloud_routing_utilization.go
  genesyscloud/resource_genesyscloud_routing_utilization_label.go
  genesyscloud/resource_genesyscloud_user.go
  genesyscloud/resource_genesyscloud_user_test.go
  genesyscloud/routing_utilization/genesyscloud_routing_utilization_init_test.go
  genesyscloud/routing_utilization/genesyscloud_routing_utilization_proxy.go
  genesyscloud/routing_utilization/resource_genesyscloud_routing_utilization.go
  genesyscloud/routing_utilization/resource_genesyscloud_routing_utilization_schema.go
  genesyscloud/routing_utilization/resource_genesyscloud_routing_utilization_test.go
  genesyscloud/routing_utilization/resource_routing_utilization_utils.go
  genesyscloud/routing_utilization_label/data_source_genesyscloud_routing_utilization_label.go
  genesyscloud/routing_utilization_label/data_source_genesyscloud_routing_utilization_label_test.go
  genesyscloud/routing_utilization_label/genesyscloud_routing_utilization_label_init_test.go
  genesyscloud/routing_utilization_label/genesyscloud_routing_utilization_label_proxy.go
  genesyscloud/routing_utilization_label/resource_genesyscloud_routing_utilization_label.go
  genesyscloud/routing_utilization_label/resource_genesyscloud_routing_utilization_label_schema.go
  genesyscloud/routing_utilization_label/resource_genesyscloud_routing_utilization_label_test.go
  genesyscloud/routing_utilization_label/resource_genesyscloud_routing_utilization_label_utils.go
  genesyscloud/tfexporter/tf_exporter_resource_test.go
  main.go
Labels: refactor

#1099 refactor/DEVTOOLING-158 idp_gsuite
  docs/resources/idp_gsuite.md
  genesyscloud/idp_gsuite/genesyscloud_idp_gsuite_proxy.go
  genesyscloud/idp_gsuite/resource_genesyscloud_idp_gsuite.go
  genesyscloud/idp_gsuite/resource_genesyscloud_idp_gsuite_init_test.go
  genesyscloud/idp_gsuite/resource_genesyscloud_idp_gsuite_schema.go
  genesyscloud/idp_gsuite/resource_genesyscloud_idp_gsuite_test.go
  genesyscloud/resource_genesyscloud_idp_gsuite.go
  genesyscloud/resource_genesyscloud_init.go
  genesyscloud/resource_genesyscloud_init_test.go
  genesyscloud/tfexporter/tf_exporter_resource_test.go
  main.go
Labels: refactor

#1102 Refactor/devtooling 160 idp_ping
  docs/resources/idp_ping.md
  genesyscloud/idp_ping/genesyscloud_idp_ping_proxy.go
  genesyscloud/idp_ping/resource_genesyscloud_idp_ping.go
  genesyscloud/idp_ping/resource_genesyscloud_idp_ping_init_test.go
  genesyscloud/idp_ping/resource_genesyscloud_idp_ping_schema.go
  genesyscloud/idp_ping/resource_genesyscloud_idp_ping_test.go
  genesyscloud/resource_genesyscloud_idp_ping.go
  genesyscloud/resource_genesyscloud_init.go
  genesyscloud/resource_genesyscloud_init_test.go
  genesyscloud/tfexporter/tf_exporter_resource_test.go
  main.go
Labels: refactor

#1127 feat/devtooling 632 added validation for ja-JP
  genesyscloud/resource_genesyscloud_knowledge_knowledgebase.go
Labels: feature
