Repository MyPureCloud/terraform-provider-genesyscloud, pull requests merged in 2024-11, with the labels that each got.

#1326 No jira: Fixing mistake in knowledge_label example resource
  docs/resources/knowledge_label.md
  examples/resources/genesyscloud_knowledge_label/resource.tf
Labels: doc, fix

#1328 bug/DEVTOOLING-898 fix for media_types conversion
  genesyscloud/outbound_digitalruleset/resource_genesyscloud_outbound_digitalruleset_utils.go
Labels: bug

#1346 added 0 check for extension
  genesyscloud/external_contacts/resource_genesyscloud_externalcontacts_contact_utils.go
Labels: bug

#1352 Fix few issues and add logs for export
  genesyscloud/tfexporter/genesyscloud_resource_exporter.go
Labels: bug

#1330 DEVTOOLING-750: Improving export speed for contact_lists and contact_lists_contacts resources
  genesyscloud/outbound_contact_list/data_source_genesyscloud_outbound_contact_list.go
  genesyscloud/outbound_contact_list/genesyscloud_outbound_contact_list_proxy.go
  genesyscloud/outbound_contact_list/resource_genesyscloud_outbound_contact_list.go
  genesyscloud/outbound_contact_list/resource_genesyscloud_outbound_contact_list_utils.go
  genesyscloud/outbound_contact_list_contact/genesyscloud_outbound_contact_list_contact_proxy.go
  genesyscloud/outbound_contact_list_contact/resource_genesyscloud_outbound_contact_list_contact.go
Labels: bug

#1361 DEVTOOLING-927: Changing `conditional_group_routing_rules.groups` to TypeSet
  docs/resources/routing_queue.md
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_members.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_schema.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_test.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_utils.go
Labels: bug

#1329 DEVTOOLING-902: Fixed bugs in pagination logic across a few packages
  genesyscloud/knowledge_document/genesyscloud_knowledge_document_proxy.go
  genesyscloud/resource_genesyscloud_knowledge_category.go
  genesyscloud/resource_genesyscloud_knowledge_knowledgebase.go
  genesyscloud/resource_genesyscloud_knowledge_label.go
  genesyscloud/team/genesyscloud_team_proxy.go
Labels: bug

#1374 Bug/devtooling 877 Airbnb - groupmembers division more than 50 with "*" issue
  genesyscloud/routing_skill_group/resource_genesyscloud_routing_skill_group_test.go
  genesyscloud/routing_skill_group/resource_genesyscloud_routing_skill_group_utils.go
Labels: bug

#1376 DEVTOOLING-924 pt3 - Add documentation regarding shared domain dictionary
  DICTIONARY.md
  README.md
Labels: feature

#1364 Feat/devtooling 651 - Integration Messaging Open
  docs/data-sources/conversations_messaging_integrations_open.md
  docs/resources/conversations_messaging_integrations_open.md
  examples/data-sources/genesyscloud_conversations_messaging_integrations_open/data-source.tf
  examples/resources/genesyscloud_conversations_messaging_integrations_open/apis.md
  examples/resources/genesyscloud_conversations_messaging_integrations_open/resource.tf
  genesyscloud/conversations_messaging_integrations_open/data_source_genesyscloud_conversations_messaging_integrations_open.go
  genesyscloud/conversations_messaging_integrations_open/data_source_genesyscloud_conversations_messaging_integrations_open_test.go
  genesyscloud/conversations_messaging_integrations_open/genesyscloud_conversations_messaging_integrations_open_init_test.go
  genesyscloud/conversations_messaging_integrations_open/genesyscloud_conversations_messaging_integrations_open_proxy.go
  genesyscloud/conversations_messaging_integrations_open/resource_genesyscloud_conversations_messaging_integrations_open.go
  genesyscloud/conversations_messaging_integrations_open/resource_genesyscloud_conversations_messaging_integrations_open_schema.go
  genesyscloud/conversations_messaging_integrations_open/resource_genesyscloud_conversations_messaging_integrations_open_test.go
  genesyscloud/conversations_messaging_integrations_open/resource_genesyscloud_conversations_messaging_integrations_open_utils.go
  genesyscloud/tfexporter/tf_exporter_resource_test.go
  main.go
Labels: feature

#1395 make docs
  docs/resources/integration_facebook.md
  docs/resources/outbound_messagingcampaign.md
Labels: doc, fix

#1392 Feat/devtooling 651 Issue fix for data_source failure
  genesyscloud/conversations_messaging_integrations_open/data_source_genesyscloud_conversations_messaging_integrations_open_test.go
Labels: feature

#1396 Small update to schedulegroups example resource
  docs/resources/architect_schedulegroups.md
  examples/resources/genesyscloud_architect_schedulegroups/resource.tf
Labels: doc, fix

#1390 Data source Race condition
  genesyscloud/tfexporter/genesyscloud_resource_exporter.go
Labels: bug
