Repository MyPureCloud/terraform-provider-genesyscloud, pull requests merged in 2024-04, with the labels that each got.

#950 Add team to custom resolver
  genesyscloud/resource_exporter/resource_exporter_custom.go
Labels: bug

#949 bug/DEVTOOLING-488: Fix User Resource Panics
  genesyscloud/resource_genesyscloud_user.go
Labels: bug

#962 Remove use_supported_content_profile
  docs/resources/webdeployments_configuration.md
  examples/resources/genesyscloud_webdeployments_configuration/resource.tf
  genesyscloud/webdeployments_configuration/resource_genesyscloud_webdeployments_configuration_schema.go
  genesyscloud/webdeployments_configuration/utils/resource_genesyscloud_webdeployments_configuration_messenger.go
Labels: feature

#953 bug/ DEVTOOLING-516: Allow Multiple inputs for BYMONTHDAY and BYMONTH
  genesyscloud/validators/validators.go
Labels: bug

#946 DEVTOOLING-417: Removed the go:generate git restore docs/index.md tag…
  docs/index.md
  genesyscloud/oauth_client/resource_genesyscloud_oauth_client.go
  genesyscloud/oauth_client/resource_genesyscloud_oauth_client_proxy.go
  go.mod
  main.go
Labels: bug

#945 feat/Devtooling-448 oauth cred cache
  genesyscloud/integration_credential/genesyscloud_integration_credential_init_test.go
  genesyscloud/integration_credential/resource_genesyscloud_integration_credential.go
  genesyscloud/integration_credential/resource_genesyscloud_integration_credential_test.go
  genesyscloud/integration_credential/resource_genesyscloud_integration_credential_utils.go
  genesyscloud/oauth_client/data_source_genesyscloud_oauth_client.go
  genesyscloud/oauth_client/data_source_genesyscloud_oauth_client_test.go
  genesyscloud/oauth_client/resource_genesyscloud_oauth_client.go
  genesyscloud/oauth_client/resource_genesyscloud_oauth_client_proxy.go
  genesyscloud/oauth_client/resource_genesyscloud_oauth_client_test.go
  genesyscloud/oauth_client/resource_genesyscloude_oauth_client_unit_test.go
  genesyscloud/team/resource_genesyscloud_team.go
Labels: feature

#961 Fix for BotFlows dependencies
  genesyscloud/dependent_consumers/genesyscloud_dependent_consumer_proxy.go
  genesyscloud/tfexporter/genesyscloud_resource_exporter.go
Labels: bug

#958 feat/Devtooling-531: Add proxy and cache to routing queue
  genesyscloud/architect_datatable_row/resource_genesyscloud_architect_datatable_row_proxy.go
  genesyscloud/architect_flow/resource_genesyscloud_architect_flow_proxy.go
  genesyscloud/architect_grammar/genesyscloud_architect_grammar_proxy.go
  genesyscloud/architect_grammar_language/genesyscloud_architect_grammar_language_proxy.go
  genesyscloud/group/genesyscloud_group_proxy.go
  genesyscloud/resource_cache/inmemory_cache.go
  genesyscloud/resource_cache/resource_cache.go
  genesyscloud/resource_cache/resource_cache_test.go
  genesyscloud/routing_queue/genesyscloud_routing_queue_proxy.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue.go
Labels: feature

#968 Fix Export cyclic deps
  genesyscloud/dependent_consumers/genesyscloud_dependent_consumer_proxy.go
  genesyscloud/tfexporter/genesyscloud_resource_exporter.go
  genesyscloud/util/util_strings.go
Labels: feature

#969 Feat/devtooling-499: Added getAll Functionality to ResponseManagement_ResponseAsset
  docs/resources/responsemanagement_responseasset.md
  genesyscloud/responsemanagement_response/resource_genesyscloud_responsemanagement_response_test.go
  genesyscloud/responsemanagement_responseasset/data_source_genesyscloud_responsemanagement_responseasset_test.go
  genesyscloud/responsemanagement_responseasset/genesyscloud_responsemanagement_responseasset_proxy.go
  genesyscloud/responsemanagement_responseasset/resource_genesyscloud_responsemanagement_responseasset.go
  genesyscloud/responsemanagement_responseasset/resource_genesyscloud_responsemanagement_responseasset_schema.go
  genesyscloud/responsemanagement_responseasset/resource_genesyscloud_responsemanagement_responseasset_test.go
  genesyscloud/responsemanagement_responseasset/resource_genesyscloud_responsemanagement_responseasset_utils.go
Labels: feature

#975 Feat/devtooling-177: Refactored orgAuthorization_pairing
  genesyscloud/orgauthorization_pairing/genesyscloud_orgauthorization_pairing_init_test.go
  genesyscloud/orgauthorization_pairing/genesyscloud_orgauthorization_pairing_proxy.go
  genesyscloud/orgauthorization_pairing/resource_genesyscloud_orgauthorization_pairing.go
  genesyscloud/orgauthorization_pairing/resource_genesyscloud_orgauthorization_pairing_schema.go
  genesyscloud/orgauthorization_pairing/resource_genesyscloud_orgauthorization_pairing_test.go
  genesyscloud/resource_genesyscloud_init.go
  genesyscloud/resource_genesyscloud_init_test.go
  genesyscloud/resource_genesyscloud_orgauthorization_pairing.go
  genesyscloud/resource_genesyscloud_user_test.go
  genesyscloud/responsemanagement_responseasset/genesyscloud_responsemanagement_responseasset_proxy.go
  genesyscloud/tfexporter/tf_exporter_resource_test.go
  main.go
Labels: feature

#974 Feature/devtooling 63
  docs/resources/routing_queue.md
  genesyscloud/routing_queue/data_source_genesyscloud_routing_queue_test.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_schema.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_test.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_utils.go
  genesyscloud/tfexporter/resource_genesyscloud_tf_export_test.go
Labels: feature

#978 Feature/devtooling 63
  genesyscloud/tfexporter/resource_genesyscloud_tf_export_test.go
Labels: feature

#981 No-Jira: Added check
  genesyscloud/routing_queue/genesyscloud_routing_queue_proxy.go
Labels: hotfix

#948 Feat/add flow log level resource
  docs/resources/flow_loglevel.md
  examples/resources/genesyscloud_flow/inboundcall_flow_example3.yaml
  examples/resources/genesyscloud_flow_loglevel/apis.md
  examples/resources/genesyscloud_flow_loglevel/resource.tf
  examples/resources/genesyscloud_processautomation_trigger/trigger_workflow_example.yaml
  genesyscloud/flow_loglevel/genesyscloud_flow_loglevel_init_test.go
  genesyscloud/flow_loglevel/genesyscloud_flow_loglevel_proxy.go
  genesyscloud/flow_loglevel/resource_genesyscloud_flow_loglevel.go
  genesyscloud/flow_loglevel/resource_genesyscloud_flow_loglevel_schema.go
  genesyscloud/flow_loglevel/resource_genesyscloud_flow_loglevel_test.go
  genesyscloud/tfexporter/tf_exporter_resource_test.go
  main.go
Labels: feature

#970 Devtooling 432: Conditonal Group Routing
  docs/resources/routing_queue.md
  docs/resources/routing_queue_conditional_group_routing.md
  examples/resources/genesyscloud_routing_queue_conditional_group_routing/apis.md
  examples/resources/genesyscloud_routing_queue_conditional_group_routing/resource.tf
  genesyscloud/routing_email_route/genesyscloud_routing_email_route_init_test.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_schema.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_test.go
  genesyscloud/routing_queue_conditional_group_routing/genesyscloud_routing_queue_conditional_group_routing_init_test.go
  genesyscloud/routing_queue_conditional_group_routing/genesyscloud_routing_queue_conditional_group_routing_proxy.go
  genesyscloud/routing_queue_conditional_group_routing/resource_genesyscloud_routing_queue_conditional_group_routing.go
  genesyscloud/routing_queue_conditional_group_routing/resource_genesyscloud_routing_queue_conditional_group_routing_schema.go
  genesyscloud/routing_queue_conditional_group_routing/resource_genesyscloud_routing_queue_conditional_group_routing_test.go
  genesyscloud/routing_queue_conditional_group_routing/resource_genesyscloud_routing_queue_conditional_group_routing_unit_test.go
  genesyscloud/tfexporter/resource_genesyscloud_tf_export_test.go
  genesyscloud/tfexporter/tf_exporter_resource_test.go
  genesyscloud/util/feature_toggles/conditional_group_routing.go
  main.go
Labels: feature

#988 Improvise exclude attributes to Regex
  genesyscloud/tfexporter/genesyscloud_resource_exporter.go
  genesyscloud/tfexporter/genesyscloud_resource_exporter_test.go
  genesyscloud/tfexporter/resource_genesyscloud_tf_export_test.go
Labels: feature

#954 feat/Devtooling 496: Routing queue Outbound email address independent resource
  docs/resources/routing_queue.md
  docs/resources/routing_queue_outbound_email_address.md
  examples/resources/genesyscloud_routing_queue_outbound_email_address/apis.md
  examples/resources/genesyscloud_routing_queue_outbound_email_address/resource.tf
  genesyscloud/routing_email_route/resource_genesyscloud_routing_email_route_test.go
  genesyscloud/routing_email_route/resource_genesyscloud_routing_email_route_utils.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_schema.go
  genesyscloud/routing_queue_conditional_group_routing/resource_genesyscloud_routing_queue_conditional_group_routing.go
  genesyscloud/routing_queue_outbound_email_address/genesyscloud_routing_queue_outbound_email_address_init_test.go
  genesyscloud/routing_queue_outbound_email_address/genesyscloud_routing_queue_outbound_email_address_proxy.go
  genesyscloud/routing_queue_outbound_email_address/resource_genesyscloud_routing_queue_outbound_email_address.go
  genesyscloud/routing_queue_outbound_email_address/resource_genesyscloud_routing_queue_outbound_email_address_schema.go
  genesyscloud/routing_queue_outbound_email_address/resource_genesyscloud_routing_queue_outbound_email_address_test.go
  genesyscloud/routing_queue_outbound_email_address/resource_genesyscloud_routing_queue_outbound_email_address_unit_test.go
  genesyscloud/tfexporter/tf_exporter_resource_test.go
  genesyscloud/util/feature_toggles/outbound_email_address.go
  main.go
Labels: feature

#996 bug/devtooling-498: [CX as Code] genesyscloud_outbound_settings export contains only null data
  docs/resources/outbound_settings.md
  genesyscloud/organization_authentication_settings/resource_genesyscloud_organization_authentication_settings.go
  genesyscloud/outbound_settings/genesyscloud_outbound_settings_proxy.go
  genesyscloud/outbound_settings/resource_genesyscloud_outbound_settings.go
  genesyscloud/outbound_settings/resource_genesyscloud_outbound_settings_schema.go
  genesyscloud/outbound_settings/resource_genesyscloud_outbound_settings_test.go
  genesyscloud/outbound_settings/resource_genesyscloud_outbound_settings_utils.go
Labels: bug

#998 DEVTOOLING-523: Flow outcomes mismatch on description
  genesyscloud/flow_outcome/resource_genesyscloud_flow_outcome.go
Labels: bug

#1001 Devtooling 561 - Members not being added correctly to teams
  genesyscloud/team/genesyscloud_team_proxy.go
  genesyscloud/team/resource_genesyscloud_team.go
  genesyscloud/team/resource_genesyscloud_team_test.go
  genesyscloud/team/resource_genesyscloud_team_utils.go
Labels: bug

#997 Fix Version Problem in WebDeployments
  genesyscloud/webdeployments_deployment/genesyscloud_webdeployments_deployment_proxy.go
  genesyscloud/webdeployments_deployment/resource_genesyscloud_webdeployments_deployment.go
  genesyscloud/webdeployments_deployment/resource_genesyscloud_webdeployments_deployment_schema.go
  genesyscloud/webdeployments_deployment/resource_genesyscloud_webdeployments_deployment_test.go
Labels: feature
