Repository MyPureCloud/terraform-provider-genesyscloud, pull requests merged in 2024-10, with the labels that each got.

#1273 Fix DEVTOOLING-855 - option for exporting computed values
  docs/resources/tf_export.md
  genesyscloud/integration_action/resource_genesyscloud_integration_action_schema.go
  genesyscloud/tfexporter/genesyscloud_resource_exporter.go
  genesyscloud/tfexporter/resource_genesyscloud_tf_export.go
Labels: fix

#1276 HOT-FIX/Devtooling-862: Added a bypass on the inactive users once th…
  genesyscloud/user/genesyscloud_user_proxy.go
Labels: hotfix

#1269 Bug/devtooling 831
  genesyscloud/outbound_contact_list_contact/genesyscloud_outbound_contact_list_contact_proxy.go
  genesyscloud/outbound_contact_list_contact/resource_genesyscloud_outbound_contact_list_contact.go
  genesyscloud/outbound_contact_list_contact/resource_genesyscloud_outbound_contact_list_contact_utils.go
Labels: bug

#1246 Bug/devtooling 615 - Consistency checker
  .gitignore
  genesyscloud/architect_emergencygroup/resource_genesyscloud_architect_emergencygroup.go
  genesyscloud/architect_emergencygroup/resource_genesyscloud_architect_emergencygroup_test.go
  genesyscloud/consistency_checker/consistency_checker.go
  genesyscloud/consistency_checker/consistency_checker_unit_test.go
  genesyscloud/consistency_checker/consistency_checker_utils.go
  genesyscloud/oauth_client/resource_genesyscloud_oauth_client.go
  genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site_schema.go
Labels: bug

#1292 Bug/devtooling 615 - Consistency Checker
  .gitignore
  genesyscloud/architect_emergencygroup/resource_genesyscloud_architect_emergencygroup.go
  genesyscloud/architect_emergencygroup/resource_genesyscloud_architect_emergencygroup_test.go
  genesyscloud/consistency_checker/consistency_checker.go
  genesyscloud/consistency_checker/consistency_checker_unit_test.go
  genesyscloud/consistency_checker/consistency_checker_utils.go
  genesyscloud/oauth_client/resource_genesyscloud_oauth_client.go
  genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site_schema.go
  genesyscloud/util/feature_toggles/consistency_checker.go
Labels: bug

#1291 Fix/devtooling 840
  docs/resources/outbound_contact_list_contact.md
  genesyscloud/outbound_contact_list_contact/resource_genesyscloud_outbound_contact_list_contact.go
  genesyscloud/outbound_contact_list_contact/resource_genesyscloud_outbound_contact_list_contact_schema.go
  genesyscloud/outbound_contact_list_contact/resource_genesyscloud_outbound_contact_list_contact_test.go
  genesyscloud/outbound_contact_list_contact/resource_genesyscloud_outbound_contact_list_contact_utils.go
Labels: fix

#1303 Bug/devtooling 870 IDP_ADFS bug on data lookup
  genesyscloud/idp_adfs/resource_genesyscloud_idp_adfs_schema.go
  genesyscloud/idp_adfs/resource_genesyscloud_idp_adfs_test.go
Labels: bug

#1310 Fixes #1301 - Nil pointer dereference in oauth_client package
  genesyscloud/oauth_client/resource_genesyscloud_oauth_client.go
Labels: bug

#1305 code fix for DEVTOOLING-762
  .github/CODEOWNERS
  docs/resources/responsemanagement_response.md
  genesyscloud/responsemanagement_response/data_source_genesyscloud_responsemanagement_response_test.go
  genesyscloud/responsemanagement_response/resource_genesyscloud_responsemanagement_response_schema.go
  genesyscloud/responsemanagement_response/resource_genesyscloud_responsemanagement_response_test.go
  genesyscloud/responsemanagement_response/resource_genesyscloud_responsemanagement_response_utils.go
  genesyscloud/responsemanagement_responseasset/data_source_genesyscloud_responsemanagement_responseasset_test.go
  genesyscloud/responsemanagement_responseasset/resource_genesyscloud_responsemanagement_responseasset_test.go
  genesyscloud/responsemanagement_responseasset/resource_genesyscloud_responsemanagement_responseasset_utils.go
  genesyscloud/util/testrunner/testrunner.go
Labels: bug

#1313 Fix DEVTOOLING-895
  genesyscloud/outbound_contact_list_contact/resource_genesyscloud_outbound_contact_list_contact.go
  genesyscloud/outbound_contact_list_contact/resource_genesyscloud_outbound_contact_list_contact_utils.go
Labels: fix

#1315 NOJIRA fix oauth client.authorized_grant_type to accept SAML2-BEARER value
  docs/resources/oauth_client.md
  genesyscloud/oauth_client/resource_genesyscloud_oauth_client_schema.go
Labels: fix

#1321 NOJIRA - Fix data resource not outputting dynamic references
  genesyscloud/tfexporter/genesyscloud_resource_exporter.go
Labels: fix
