Repository MyPureCloud/terraform-provider-genesyscloud, pull requests merged in 2025-03, with the labels that each got.

#1585 DEVTOOLING-1099: fix email_route nil pointer dereference + refactorings
  genesyscloud/routing_email_route/genesyscloud_routing_email_route_proxy.go
  genesyscloud/routing_email_route/resource_genesyscloud_routing_email_route.go
  genesyscloud/routing_email_route/resource_genesyscloud_routing_email_route_unit_test.go
  genesyscloud/routing_email_route/resource_genesyscloud_routing_email_route_utils.go
Labels: bug

#1532 Fixing DEVTOOLING-1071 with the help from Amazon Q
  genesyscloud/provider/provider.go
  genesyscloud/provider/provider_schema.go
  genesyscloud/provider/provider_test.go
  genesyscloud/provider/sdk_client_pool.go
  genesyscloud/provider/sdk_client_pool_test.go
  genesyscloud/tfexporter/genesyscloud_resource_exporter.go
  genesyscloud/tfexporter/resource_genesyscloud_tf_export_test.go
  genesyscloud/tfexporter/tfstate_exporter.go
  jenkins/tests/Jenkinsfile
Labels: fix

#1592 Feature DEVTOOLING-1103
  .gitignore
  .goreleaser.yml
  genesyscloud/platform/platform.go
  genesyscloud/provider_registrar/provider_registrar.go
  go.mod
  tools/dependency_tree/dependency_tree.go
Labels: feature

#1609 DEVTOOLING-1135 Fix the block label for the integration credential
  genesyscloud/integration_credential/resource_genesyscloud_integration_credential.go
Labels: fix

#1612 Fixes DEVTOOLING-1137 by only outputting unresolveable attributes for non-data resource block types
  genesyscloud/tfexporter/genesyscloud_resource_exporter.go
Labels: fix

#1577 Feat/gpe 14858 update segment contract
  docs/resources/journey_segment.md
  genesyscloud/journey_segment/resource_genesyscloud_journey_segment_schema.go
  genesyscloud/journey_segment/resource_genesyscloud_journey_segment_utils.go
  test/data/data_source/genesyscloud_journey_segment/find_by_name/01_find_by_name.tf
  test/data/resource/genesyscloud_journey_segment/basic_attributes/01_basic_resource.tf
  test/data/resource/genesyscloud_journey_segment/basic_attributes/02_update_attributes.tf
  test/data/resource/genesyscloud_journey_segment/context_only_to_journey_only/01_create_context_only.tf
  test/data/resource/genesyscloud_journey_segment/context_only_to_journey_only/02_update_to_journey_only.tf
  test/data/resource/genesyscloud_journey_segment/context_only_to_journey_only/03_update_add_criteria.tf
  test/data/resource/genesyscloud_journey_segment/context_only_to_journey_only/04_update_add_pattern.tf
  test/data/resource/genesyscloud_journey_segment/optional_attributes/01_create.tf
  test/data/resource/genesyscloud_journey_segment/optional_attributes/02_update_all_optional_changed.tf
  test/data/resource/genesyscloud_journey_segment/optional_attributes/03_update_remove_description.tf
Labels: feature
