Repository MyPureCloud/terraform-provider-genesyscloud, pull requests merged in 2025-02, with the labels that each got.

#1523 Fix/devtooling 907
  genesyscloud/telephony_providers_edges_phone/resource_genesyscloud_telephony_providers_edges_phone.go
Labels: bug

#1517 DEVTOOLING-1064 Fix telephony issues
  genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site_utils.go
  genesyscloud/telephony_providers_edges_site_outbound_route/resource_genesyscloud_telephony_providers_edges_site_outbound_route.go
Labels: fix

#1520 Fixes DEVTOOLING-1066 - Trunkbasesettings cache hydrating
  genesyscloud/telephony_provider_edges_trunkbasesettings/genesyscloud_telephony_providers_trunkbasesettings_proxy.go
  genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site.go
Labels: fix

#1506 Feature/devtooling-1019 Bulk Contact Management within the Contact Lists resource
  docs/resources/outbound_contact_list.md
  docs/resources/outbound_contact_list_contact.md
  docs/resources/widget_deployment.md
  examples/resources/genesyscloud_flow/inboundcall_flow_example.yaml
  examples/resources/genesyscloud_outbound_contact_list_contact/apis.md
  examples/resources/genesyscloud_widget_deployment/apis.md
  genesyscloud/architect_grammar_language/resource_genesyscloud_architect_grammar_language_utils.go
  genesyscloud/architect_user_prompt/resource_genesyscloud_architect_user_prompt_utils.go
  genesyscloud/data_source_genesyscloud_journey_segment_test.go
  genesyscloud/journey_action_map/data_source_genesyscloud_journey_action_map_test.go
  genesyscloud/journey_action_map/resource_genesyscloud_journey_action_map_test.go
  genesyscloud/journey_action_template/data_source_genesyscloud_journey_action_template_test.go
  genesyscloud/journey_action_template/resource_genesyscloud_journey_action_template_test.go
  genesyscloud/journey_outcome/data_source_genesyscloud_journey_outcome_test.go
  genesyscloud/journey_outcome/resource_genesyscloud_journey_outcome_test.go
  genesyscloud/outbound_contact_list/data_source_genesyscloud_outbound_contact_list.go
  genesyscloud/outbound_contact_list/genesyscloud_outbound_contact_list_proxy.go
  genesyscloud/outbound_contact_list/resource_genesyscloud_outbound_contact_list.go
  genesyscloud/outbound_contact_list/resource_genesyscloud_outbound_contact_list_schema.go
  genesyscloud/outbound_contact_list/resource_genesyscloud_outbound_contact_list_test.go
  genesyscloud/outbound_contact_list/resource_genesyscloud_outbound_contact_list_utils.go
  genesyscloud/outbound_contact_list/resource_genesyscloud_outbound_contact_list_utils_test.go
  genesyscloud/outbound_contact_list_contact/genesyscloud_outbound_contact_list_contact_proxy.go
  genesyscloud/outbound_contact_list_contact/resource_genesyscloud_outbound_contact_list_contact.go
  genesyscloud/outbound_contact_list_contact/resource_genesyscloud_outbound_contact_list_contact_schema.go
  genesyscloud/provider/provider.go
  genesyscloud/provider/provider_utils.go
  genesyscloud/resource_genesyscloud_journey_segment_test.go
  genesyscloud/resource_genesyscloud_widget_deployment.go
  genesyscloud/responsemanagement_responseasset/resource_genesyscloud_responsemanagement_responseasset_utils.go
  genesyscloud/scripts/genesyscloud_scripts_proxy.go
  genesyscloud/scripts/resource_genesyscloud_script_utils.go
  genesyscloud/tfexporter/resource_genesyscloud_tf_export_test.go
  genesyscloud/tfexporter/tf_exporter_resource_test.go
  genesyscloud/util/files/util_files.go
  genesyscloud/util/files/util_files_test.go
  genesyscloud/util/testrunner/testrunner.go
  genesyscloud/util/testrunner/testrunner_test.go
  genesyscloud/validators/validators.go
  genesyscloud/validators/validators_test.go
  templates/resources.md.tmpl
Labels: feature

#1528 Fix/devtooling 907
  genesyscloud/telephony_providers_edges_phone/resource_genesyscloud_telephony_providers_edges_phone.go
Labels: bug

#1527 DEVTOOLING-1065 Add handling for Windows platforms
  genesyscloud/platform/platform.go
Labels: fix

#1531 Fix Routing Skills.
  genesyscloud/user/resource_genesyscloud_user_schema.go
  genesyscloud/user/resource_genesyscloud_user_utils.go
Labels: feature

#1543 Update platform fix
  genesyscloud/platform/platform.go
  genesyscloud/provider/provider.go
  genesyscloud/tfexporter/tfstate_exporter.go
Labels: bug

#1526 Feat/devtooling 823 - Add description to the Genesys Cloud routing wrapup code resource
  docs/resources/routing_wrapupcode.md
  examples/resources/genesyscloud_routing_wrapupcode/resource.tf
  genesyscloud/outbound_callanalysisresponseset/resource_genesyscloud_outbound_callanalysisresponseset_test.go
  genesyscloud/outbound_campaign/resource_genesyscloud_outbound_campaign_test.go
  genesyscloud/outbound_campaign/resource_genesyscloud_outbound_campaign_utils.go
  genesyscloud/outbound_wrapupcode_mappings/resource_genesyscloud_outbound_wrapupcode_mappings_test.go
  genesyscloud/recording_media_retention_policy/data_source_genesyscloud_recording_media_retention_policy_test.go
  genesyscloud/recording_media_retention_policy/resource_genesyscloud_recording_media_retention_policy_test.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_test.go
  genesyscloud/routing_wrapupcode/data_source_genesyscloud_routing_wrapupcode_test.go
  genesyscloud/routing_wrapupcode/resource_genesyscloud_routing_wrapupcode.go
  genesyscloud/routing_wrapupcode/resource_genesyscloud_routing_wrapupcode_schema.go
  genesyscloud/routing_wrapupcode/resource_genesyscloud_routing_wrapupcode_test.go
  genesyscloud/tfexporter/resource_genesyscloud_tf_export_test.go
Labels: feature

#1518 [GRID-2681] Add support for journey view schedule resource -
  docs/resources/journey_view_schedule.md
  examples/resources/genesyscloud_journey_view_schedule/apis.md
  examples/resources/genesyscloud_journey_view_schedule/resource.tf
  genesyscloud/journey_view_schedule/genesyscloud_journey_view_schedule_init_test.go
  genesyscloud/journey_view_schedule/genesyscloud_journey_view_schedule_proxy.go
  genesyscloud/journey_view_schedule/resource_genesyscloud_journey_view_schedule.go
  genesyscloud/journey_view_schedule/resource_genesyscloud_journey_view_schedule_test.go
  genesyscloud/journey_view_schedule/resource_genesyscloud_journey_views_schedules_schema.go
  genesyscloud/tfexporter/tf_exporter_resource_test.go
  main.go
Labels: feature

#1525 DEVTOOLING-929: Converting groups in CGR rules.groups from TypeList to TypeSet
  docs/resources/routing_queue_conditional_group_routing.md
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_utils.go
  genesyscloud/routing_queue_conditional_group_routing/genesyscloud_routing_queue_conditional_group_routing_utils.go
  genesyscloud/routing_queue_conditional_group_routing/resource_genesyscloud_routing_queue_conditional_group_routing.go
  genesyscloud/routing_queue_conditional_group_routing/resource_genesyscloud_routing_queue_conditional_group_routing_schema.go
  genesyscloud/routing_queue_conditional_group_routing/resource_genesyscloud_routing_queue_conditional_group_routing_unit_test.go
Labels: bug

#1549 NOJIRA Fix some path resolutions
  genesyscloud/outbound_contact_list/resource_genesyscloud_outbound_contact_list_utils.go
  genesyscloud/outbound_contact_list/resource_genesyscloud_outbound_contact_list_utils_test.go
  genesyscloud/tfexporter/genesyscloud_resource_exporter.go
  genesyscloud/tfexporter/resource_genesyscloud_tf_export_test.go
Labels: fix

#1539 Bug/devtooling 921 add callback attributes
  docs/resources/routing_queue.md
  examples/resources/genesyscloud_flow/inboundcall_flow_example.yaml
  examples/resources/genesyscloud_flow/inboundcall_flow_example2.yaml
  examples/resources/genesyscloud_flow/inboundcall_flow_example3.yaml
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_schema.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_test.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_unit_test.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_utils.go
Labels: bug

#1551 Feature/devtooling 931
  docs/resources/organization_authentication_settings.md
  genesyscloud/organization_authentication_settings/genesyscloud_organization_authentication_settings_proxy.go
  genesyscloud/organization_authentication_settings/resource_genesyscloud_organization_authentication_settings.go
  genesyscloud/organization_authentication_settings/resource_genesyscloud_organization_authentication_settings_schema.go
  genesyscloud/organization_authentication_settings/resource_genesyscloud_organization_authentication_settings_unit_test.go
  genesyscloud/organization_authentication_settings/resource_genesyscloud_organization_authentication_settings_utils.go
Labels: feature

#1560 Fix Journey Test cases
  genesyscloud/journey_action_map/genesyscloud_journey_action_map_proxy.go
  genesyscloud/journey_segment/genesyscloud_journey_segment_proxy.go
  genesyscloud/routing_queue/data_source_genesyscloud_routing_queue.go
Labels: bug

#1554 Feature/devtooling 987
  docs/resources/recording_media_retention_policy.md
  genesyscloud/recording_media_retention_policy/resource_genesyscloud_recording_media_retention_policy_schema.go
  genesyscloud/recording_media_retention_policy/resource_genesyscloud_recording_media_retention_policy_test.go
  genesyscloud/recording_media_retention_policy/resource_genesyscloud_recording_media_retention_policy_utils.go
Labels: feature

#1546 Bug/devtooling 1005 - PUT api call to set ownerIds as empty array
  genesyscloud/group/resource_genesyscloud_group.go
  genesyscloud/group/resource_genesyscloud_group_test.go
Labels: bug

#1545 Fix/provider platform issues2
  genesyscloud/tfexporter/tfstate_exporter.go
  go.sum
Labels: fix

#1564 DEVTOOLING-1093 - Fix nil pointer issues in externalcontacts org
  genesyscloud/external_contacts_organization/resource_genesyscloud_externalcontacts_organization_utils.go
Labels: fix

#1561 Fix DEVTOOLING-1088 - User password creation issue
  genesyscloud/user/resource_genesyscloud_user.go
  genesyscloud/user/resource_genesyscloud_user_test.go
Labels: fix

#1562 Fix/devtooling 1087
  genesyscloud/routing_queue/data_source_genesyscloud_routing_queue.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_schema.go
Labels: fix

#1570 No JIRA: fix import cycle
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_schema.go
Labels: bug

#1569 fix for DEVTOOLING-1091
  genesyscloud/routing_email_route/genesyscloud_routing_email_route_proxy.go
  genesyscloud/routing_email_route/resource_genesyscloud_routing_email_route_utils.go
Labels: bug

#1571 Fix test case
  genesyscloud/tfexporter/resource_genesyscloud_tf_export_test.go
Labels: feature

#1580 No JIRA: Fixed bug with media_settings_callback mode attr
  docs/resources/routing_queue.md
  examples/resources/genesyscloud_flow/inboundcall_flow_example.yaml
  examples/resources/genesyscloud_flow/inboundcall_flow_example2.yaml
  examples/resources/genesyscloud_flow/inboundcall_flow_example3.yaml
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_schema.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_test.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_utils.go
Labels: bug
