Repository MyPureCloud/terraform-provider-genesyscloud, pull requests merged in 2025-01, with the labels that each got.

#1442 Fix DEVTOOLING-936 (update)
  genesyscloud/telephony_providers_edges_site/genesyscloud_telephony_providers_edges_site_proxy.go
  genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site.go
  genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site_utils.go
  genesyscloud/telephony_providers_edges_site_outbound_route/resource_genesyscloud_telephony_providers_edges_site_outbound_route.go
Labels: fix

#1439 Fixes DEVTOOLING-988
  genesyscloud/tfexporter/export_common.go
  genesyscloud/tfexporter/genesyscloud_resource_exporter.go
  genesyscloud/tfexporter/genesyscloud_resource_exporter_test.go
  genesyscloud/tfexporter/hcl_exporter.go
  genesyscloud/tfexporter/json_exporter.go
Labels: fix

#1432 Fix/devtooling 936
  docs/resources/telephony_providers_edges_site.md
  docs/resources/telephony_providers_edges_site_outbound_route.md
  docs/resources/telephony_providers_edges_trunkbasesettings.md
  docs/resources/tf_export.md
  examples/resources/genesyscloud_telephony_providers_edges_site/apis.md
  examples/resources/genesyscloud_telephony_providers_edges_site_outbound_route/apis.md
  examples/resources/genesyscloud_telephony_providers_edges_trunkbasesettings/apis.md
  genesyscloud/resource_exporter/resource_exporter.go
  genesyscloud/telephony_provider_edges_trunkbasesettings/genesyscloud_telephony_providers_trunkbasesettings_schema.go
  genesyscloud/telephony_provider_edges_trunkbasesettings/resource_genesyscloud_telephony_providers_edges_trunkbasesettings.go
  genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site.go
  genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site_schema.go
  genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site_utils.go
  genesyscloud/telephony_providers_edges_site_outbound_route/resource_genesyscloud_telephony_providers_edges_site_outbound_route_schema.go
  genesyscloud/telephony_providers_edges_site_outbound_route/resource_genesyscloud_telephony_providers_edges_site_outbound_route_utils.go
  genesyscloud/tfexporter/genesyscloud_resource_exporter.go
  genesyscloud/tfexporter/genesyscloud_resource_exporter_test.go
  genesyscloud/tfexporter/resource_genesyscloud_tf_export.go
  genesyscloud/tfexporter/tfstate_exporter.go
  genesyscloud/util/lists/util_lists.go
Labels: fix

#1448 add email route
  docs/resources/routing_email_route.md
  genesyscloud/routing_email_route/resource_genesyscloud_routing_email_route.go
  genesyscloud/routing_email_route/resource_genesyscloud_routing_email_route_schema.go
  genesyscloud/routing_email_route/resource_genesyscloud_routing_email_route_test.go
  genesyscloud/routing_email_route/resource_genesyscloud_routing_email_route_utils.go
Labels: feature

#1454 Read retry before assigning user
  genesyscloud/telephony_providers_edges_phone/resource_genesyscloud_telephony_providers_edges_phone.go
  genesyscloud/telephony_providers_edges_phone/resource_genesyscloud_telephony_providers_edges_phone_utils.go
Labels: bug

#1453 Update resources in architect prompt
  genesyscloud/architect_user_prompt/genesyscloud_architect_user_prompt_proxy.go
Labels: bug

#1459 NOJIRA - Default Outbound Routes Creation Logic Tweak
  genesyscloud/telephony_providers_edges_site_outbound_route/resource_genesyscloud_telephony_providers_edges_site_outbound_route.go
Labels: fix

#1457 NOJIRA - Fix/outbound route cache
  docs/resources/telephony_providers_edges_site_outbound_route.md
  examples/resources/genesyscloud_telephony_providers_edges_site_outbound_route/apis.md
  genesyscloud/telephony_providers_edges_site_outbound_route/genesyscloud_telephony_providers_edges_site_outbound_route_proxy.go
Labels: fix

#1479 tweak diagnostics
  genesyscloud/util/util_diagnostic_unit_test.go
  genesyscloud/util/util_diagnostics.go
Labels: bug

#1481 Tweak Diagnostics
  genesyscloud/util/util_diagnostic_unit_test.go
  genesyscloud/util/util_diagnostics.go
Labels: bug

#1463 Fixes DEVTOOLING-1029
  genesyscloud/platform/platform.go
  genesyscloud/platform/platform_test.go
  genesyscloud/provider/provider.go
  genesyscloud/tfexporter/genesyscloud_resource_exporter.go
  genesyscloud/tfexporter/hcl_exporter.go
  genesyscloud/tfexporter/json_exporter.go
  genesyscloud/tfexporter/tfstate_exporter.go
  go.mod
  go.sum
Labels: fix

#1483 Update empty resources section for architect prompt
  genesyscloud/architect_user_prompt/genesyscloud_architect_user_prompt_proxy.go
  genesyscloud/architect_user_prompt/resource_architect_user_prompt_schema.go
  genesyscloud/architect_user_prompt/resource_genesyscloud_architect_user_prompt_utils.go
Labels: bug

#1474 used scan endpoint
  genesyscloud/external_contacts_organization/data_source_genesyscloud_externalcontacts_organization.go
  genesyscloud/external_contacts_organization/genesyscloud_externalcontacts_organization_proxy.go
  genesyscloud/external_contacts_organization/resource_genesyscloud_externalcontacts_organization.go
Labels: bug

#1496 Fix/devtooling 1029
  genesyscloud/platform/platform.go
  genesyscloud/platform/platform_test.go
  genesyscloud/provider/provider.go
  genesyscloud/tfexporter/genesyscloud_resource_exporter.go
  genesyscloud/tfexporter/hcl_exporter.go
  genesyscloud/tfexporter/json_exporter.go
  genesyscloud/tfexporter/tfstate_exporter.go
  go.mod
  go.sum
Labels: fix

#1504 fix prompts
  genesyscloud/architect_user_prompt/resource_architect_user_prompt_schema.go
  genesyscloud/architect_user_prompt/resource_genesyscloud_architect_user_prompt_utils.go
Labels: bug

#1503 fix prompt export
  genesyscloud/architect_user_prompt/resource_architect_user_prompt_schema.go
  genesyscloud/architect_user_prompt/resource_genesyscloud_architect_user_prompt_utils.go
Labels: bug

#1508 NOJIRA - Fix NPE
  genesyscloud/telephony_providers_edges_site/resource_genesyscloud_telephony_providers_edges_site.go
Labels: fix

#1501 Fix/devtooling-1029 - Determine Platform Binary to correctly run Terraform commands and populate correct registry
  genesyscloud/platform/platform.go
  genesyscloud/platform/platform_test.go
  genesyscloud/provider/provider.go
  genesyscloud/tfexporter/genesyscloud_resource_exporter.go
  genesyscloud/tfexporter/hcl_exporter.go
  genesyscloud/tfexporter/json_exporter.go
  genesyscloud/tfexporter/tfstate_exporter.go
  go.mod
  go.sum
Labels: fix

#1455 feature/DEVTOOLING-166
  genesyscloud/data_source_genesyscloud_journey_outcome.go
  genesyscloud/external_contacts_external_source/genesyscloud_externalcontacts_external_source_proxy.go
  genesyscloud/external_contacts_external_source/resource_genesyscloud_externalcontacts_external_source.go
  genesyscloud/external_contacts_external_source/resource_genesyscloud_externalcontacts_external_source_test.go
  genesyscloud/external_contacts_external_source/resource_genesyscloud_externalcontacts_external_source_utils.go
  genesyscloud/journey_outcome/data_source_genesyscloud_journey_outcome.go
  genesyscloud/journey_outcome/data_source_genesyscloud_journey_outcome_test.go
  genesyscloud/journey_outcome/genesyscloud_journey_outcome_init_test.go
  genesyscloud/journey_outcome/genesyscloud_journey_outcome_proxy.go
  genesyscloud/journey_outcome/resource_genesyscloud_journey_outcome.go
  genesyscloud/journey_outcome/resource_genesyscloud_journey_outcome_schema.go
  genesyscloud/journey_outcome/resource_genesyscloud_journey_outcome_test.go
  genesyscloud/journey_outcome/resource_genesyscloud_journey_outcome_utils.go
  genesyscloud/journey_outcome_predictor/genesyscloud_journey_outcome_predictor_init_test.go
  genesyscloud/resource_genesyscloud_init.go
  genesyscloud/resource_genesyscloud_init_test.go
  genesyscloud/resource_genesyscloud_journey_outcome.go
  genesyscloud/tfexporter/tf_exporter_resource_test.go
  genesyscloud/util/testrunner/testrunner.go
  main.go
Labels: feature

#1512 NO-JIRA Tech Debt sweep of items that came up during development on other PRs
  .gitignore
  genesyscloud/architect_emergencygroup/resource_genesyscloud_architect_emergencygroup_test.go
  genesyscloud/architect_flow/data_source_genesyscloud_flow_test.go
  genesyscloud/architect_flow/resource_genesyscloud_architect_flow_utils.go
  genesyscloud/architect_flow/resource_genesyscloud_flow_test.go
  genesyscloud/architect_grammar_language/resource_genesyscloud_architect_grammar_language_test.go
  genesyscloud/architect_grammar_language/resource_genesyscloud_architect_grammar_language_utils.go
  genesyscloud/architect_user_prompt/resource_genesyscloud_architect_user_prompt_test.go
  genesyscloud/architect_user_prompt/resource_genesyscloud_architect_user_prompt_utils.go
  genesyscloud/flow_loglevel/resource_genesyscloud_flow_loglevel_test.go
  genesyscloud/journey_action_map/resource_genesyscloud_journey_action_map_test.go
  genesyscloud/outbound_callanalysisresponseset/resource_genesyscloud_outbound_callanalysisresponseset_test.go
  genesyscloud/outbound_campaign/data_source_genesyscloud_outbound_campaign_test.go
  genesyscloud/outbound_campaign/resource_genesyscloud_outbound_campaign_test.go
  genesyscloud/outbound_campaignrule/data_source_genesyscloud_outbound_campaignrule_test.go
  genesyscloud/outbound_campaignrule/resource_genesyscloud_outbound_campaignrule_test.go
  genesyscloud/outbound_contact_list/resource_genesyscloud_outbound_contact_list_utils_test.go
  genesyscloud/outbound_sequence/data_source_genesyscloud_outbound_sequence_test.go
  genesyscloud/outbound_sequence/resource_genesyscloud_outbound_sequence_test.go
  genesyscloud/platform/platform.go
  genesyscloud/platform/platform_test.go
  genesyscloud/process_automation_trigger/data_source_genesyscloud_processautomation_trigger_test.go
  genesyscloud/process_automation_trigger/resource_genesyscloud_processautomation_trigger_test.go
  genesyscloud/recording_media_retention_policy/resource_genesyscloud_recording_media_retention_policy_test.go
  genesyscloud/responsemanagement_responseasset/data_source_genesyscloud_responsemanagement_responseasset_test.go
  genesyscloud/responsemanagement_responseasset/resource_genesyscloud_responsemanagement_responseasset_test.go
  genesyscloud/responsemanagement_responseasset/resource_genesyscloud_responsemanagement_responseasset_utils.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_test.go
  genesyscloud/scripts/data_source_genesyscloud_script_test.go
  genesyscloud/scripts/resource_genesyscloud_script_test.go
  genesyscloud/scripts/resource_genesyscloud_script_utils.go
  genesyscloud/tfexporter/resource_genesyscloud_tf_export_test.go
  genesyscloud/tfexporter/tfstate_exporter.go
  genesyscloud/util/testrunner/testrunner.go
  genesyscloud/util/testrunner/testrunner_test.go
  test/data/resource/genesyscloud_architect_grammar_language/dtmf-gram-01.gram
  test/data/resource/genesyscloud_architect_grammar_language/dtmf-gram-02.gram
  test/data/resource/genesyscloud_architect_grammar_language/dtmf-grxml-01.grxml
  test/data/resource/genesyscloud_architect_grammar_language/dtmf-grxml-02.grxml
  test/data/resource/genesyscloud_architect_grammar_language/voice-gram-01.gram
  test/data/resource/genesyscloud_architect_grammar_language/voice-gram-02.gram
  test/data/resource/genesyscloud_architect_grammar_language/voice-grxml-01.grxml
  test/data/resource/genesyscloud_architect_grammar_language/voice-grxml-02.grxml
  test/data/resource/genesyscloud_architect_user_prompt/test-prompt-01.wav
  test/data/resource/genesyscloud_architect_user_prompt/test-prompt-02.wav
Labels: fix
