Repository MyPureCloud/terraform-provider-genesyscloud, pull requests merged in 2025-06, with the labels that each got.

#1744 Fixes the TestAccResourceTfExportExcludeFilterResources.* tests
  genesyscloud/tfexporter/resource_genesyscloud_tf_export_test.go
Labels: fix

#1752 Data Source fix for Dependency Resolution
  genesyscloud/tfexporter/genesyscloud_resource_exporter.go
Labels: feature

#1757 (DEVTOOLING-1224) Docs update to aid regex filtering on export
  docs/guides/export.md
  docs/resources/flow.md
  docs/resources/integration_action_draft.md
  docs/resources/knowledge_document.md
  docs/resources/knowledge_document_variation.md
  docs/resources/knowledge_label.md
  docs/resources/user.md
  examples/resources/genesyscloud_integration_action_draft/resource.tf
  genesyscloud/architect_flow/resource_genesyscloud_architect_flow_schema.go
  genesyscloud/knowledge_document/resource_genesyscloud_knowledge_document_schema.go
  genesyscloud/knowledge_document_variation/resource_genesyscloud_knowledge_document_variation_schema.go
  genesyscloud/knowledge_label/resource_genesyscloud_knowledge_label_schema.go
  genesyscloud/user/resource_genesyscloud_user_schema.go
  templates/guides/export.md.tmpl
Labels: doc

#1736 bug DEVTOOLING-1208 fixed
  genesyscloud/responsemanagement_responseasset/resource_genesyscloud_responsemanagement_responseasset_utils.go
Labels: bug
