Repository MyPureCloud/terraform-provider-genesyscloud, pull requests merged in 2025-05, with the labels that each got.

#1688 Fix test cases
  genesyscloud/conversations_messaging_integrations_whatsapp/data_source_genesyscloud_conversations_messaging_integrations_whatsapp_test.go
  genesyscloud/knowledge_document/resource_genesyscloud_knowledge_document_test.go
  genesyscloud/knowledge_document_variation/data_source_genesyscloud_knowledge_document_variation_test.go
  genesyscloud/knowledge_document_variation/resource_genesyscloud_knowledge_document_variation_test.go
  genesyscloud/webdeployments_configuration/resource_genesyscloud_webdeployments_configuration_test.go
Labels: feature

#1696 line to be ascertained from phone base
  genesyscloud/telephony_providers_edges_phone/resource_genesyscloud_telephony_providers_edges_phone_utils.go
Labels: bug

#1704 NO-JIRA Fix bug where failures to add members to teams were not being surfaced
  genesyscloud/team/resource_genesyscloud_team_utils.go
Labels: fix

#1695 (DEVTOOLING-1146) genesyscloud_tf_export: Duplicate data actions were not all appearing in exported state file
  genesyscloud/integration_action/resource_genesyscloud_integration_action.go
  genesyscloud/integration_action/resource_genesyscloud_integration_action_utils.go
  genesyscloud/resource_exporter/resource_exporter_unit_test.go
  genesyscloud/resource_exporter/resource_name_sanitizer.go
  genesyscloud/resource_exporter/resource_name_sanitizer_test.go
  genesyscloud/tfexporter/genesyscloud_resource_exporter.go
  genesyscloud/tfexporter/tfstate_exporter.go
  genesyscloud/util/feature_toggles/exporter_sanitizer.go
  genesyscloud/util/lists/util_lists.go
Labels: bug

#1701 NOJIRA - Fix genesys routing email route self referential issues
  docs/resources/routing_email_route.md
  genesyscloud/routing_email_route/resource_genesyscloud_routing_email_route.go
  genesyscloud/routing_email_route/resource_genesyscloud_routing_email_route_schema.go
  genesyscloud/routing_email_route/resource_genesyscloud_routing_email_route_test.go
  genesyscloud/routing_email_route/resource_genesyscloud_routing_email_route_utils.go
Labels: fix

#1702 NO-JIRA fix issue with flow outcomes where a creation fails if it already exists.
  genesyscloud/flow_outcome/genesyscloud_flow_outcome_proxy.go
  genesyscloud/flow_outcome/resource_genesyscloud_flow_outcome.go
Labels: fix

#1709 Util list hardening to prevent nil dereference panics
  genesyscloud/util/lists/util_lists.go
  genesyscloud/util/lists/util_lists_test.go
Labels: fix

#1712 (NO-JIRA) genesyscloud_flow_outcome: Docs update
  docs/resources/flow_outcome.md
  genesyscloud/flow_outcome/resource_genesyscloud_flow_outcome_schema.go
Labels: doc

#1628 feat/DEVTOOLING-844 add new genesyscloud resource for "presence status" management
  docs/resources/organization_presence_definition.md
  examples/resources/genesyscloud_organization_presence_definition/apis.md
  examples/resources/genesyscloud_organization_presence_definition/resource.tf
  genesyscloud/organization_presence_definition/genesyscloud_organization_presence_definition_init_test.go
  genesyscloud/organization_presence_definition/genesyscloud_organization_presence_definition_proxy.go
  genesyscloud/organization_presence_definition/resource_genesyscloud_organization_presence_definition.go
  genesyscloud/organization_presence_definition/resource_genesyscloud_organization_presence_definition_schema.go
  genesyscloud/organization_presence_definition/resource_genesyscloud_organization_presence_definition_test.go
  genesyscloud/provider_registrar/provider_registrar.go
  genesyscloud/validators/validators.go
Labels: feature

#1714 Feature/failing build
  genesyscloud/organization_presence_definition/genesyscloud_organization_presence_definition_init_test.go
  genesyscloud/organization_presence_definition/genesyscloud_organization_presence_definition_proxy.go
  genesyscloud/organization_presence_definition/resource_genesyscloud_organization_presence_definition.go
  genesyscloud/organization_presence_definition/resource_genesyscloud_organization_presence_definition_test.go
Labels: feature

#1713 resolve data sources for dependson
  genesyscloud/tfexporter/genesyscloud_resource_exporter.go
Labels: feature

#1683 DEVTOOLING-179 refactor
  docs/data-sources/quality_forms_survey.md
  genesyscloud/provider_registrar/provider_registrar.go
  genesyscloud/quality_forms_survey/data_source_genesyscloud_quality_forms_survey.go
  genesyscloud/quality_forms_survey/data_source_genesyscloud_quality_forms_survey_test.go
  genesyscloud/quality_forms_survey/genesyscloud_quality_forms_survey_init_test.go
  genesyscloud/quality_forms_survey/genesyscloud_quality_forms_survey_proxy.go
  genesyscloud/quality_forms_survey/resource_genesyscloud_quality_forms_survey.go
  genesyscloud/quality_forms_survey/resource_genesyscloud_quality_forms_survey_schema.go
  genesyscloud/quality_forms_survey/resource_genesyscloud_quality_forms_survey_test.go
  genesyscloud/quality_forms_survey/resource_genesyscloud_quality_forms_survey_utils.go
  genesyscloud/recording_media_retention_policy/data_source_genesyscloud_recording_media_retention_policy_test.go
  genesyscloud/recording_media_retention_policy/genesyscloud_recording_media_retention_policy_init_test.go
  genesyscloud/recording_media_retention_policy/resource_genesyscloud_recording_media_retention_policy.go
  genesyscloud/recording_media_retention_policy/resource_genesyscloud_recording_media_retention_policy_test.go
  genesyscloud/resource_genesyscloud_init.go
  genesyscloud/resource_genesyscloud_init_test.go
  genesyscloud/resource_genesyscloud_quality_forms_survey.go
  genesyscloud/tfexporter/tf_exporter_resource_test.go
Labels: feature

#1700 refactor DEVTOOLING-178
  genesyscloud/data_source_genesyscloud_quality_forms_evaluation.go
  genesyscloud/provider_registrar/provider_registrar.go
  genesyscloud/quality_forms_evaluation/data_source_genesyscloud_quality_forms_evaluation.go
  genesyscloud/quality_forms_evaluation/data_source_genesyscloud_quality_forms_evaluation_test.go
  genesyscloud/quality_forms_evaluation/genesyscloud_quality_forms_evaluation_init_test.go
  genesyscloud/quality_forms_evaluation/genesyscloud_quality_forms_evaluation_proxy.go
  genesyscloud/quality_forms_evaluation/resource_genesyscloud_quality_forms_evaluation.go
  genesyscloud/quality_forms_evaluation/resource_genesyscloud_quality_forms_evaluation_schema.go
  genesyscloud/quality_forms_evaluation/resource_genesyscloud_quality_forms_evaluation_test.go
  genesyscloud/quality_forms_evaluation/resource_genesyscloud_quality_forms_evaluation_utils.go
  genesyscloud/quality_forms_survey/data_source_genesyscloud_quality_forms_survey_test.go
  genesyscloud/quality_forms_survey/resource_genesyscloud_quality_forms_survey_test.go
  genesyscloud/recording_media_retention_policy/data_source_genesyscloud_recording_media_retention_policy_test.go
  genesyscloud/recording_media_retention_policy/genesyscloud_recording_media_retention_policy_init_test.go
  genesyscloud/recording_media_retention_policy/resource_genesyscloud_recording_media_retention_policy_test.go
  genesyscloud/resource_genesyscloud_init.go
  genesyscloud/resource_genesyscloud_init_test.go
  genesyscloud/resource_genesyscloud_quality_forms_evaluation.go
  genesyscloud/resource_genesyscloud_quality_forms_evaluation_test.go
  genesyscloud/tfexporter/resource_genesyscloud_tf_export_test.go
  genesyscloud/tfexporter/tf_exporter_resource_test.go
Labels: feature

#1725 (NO-JIRA) genesyscloud_organization_presence_definition: Removing validators to fix export
  docs/resources/organization_presence_definition.md
  genesyscloud/organization_presence_definition/resource_genesyscloud_organization_presence_definition_schema.go
Labels: fix

#1732 (NO-JIRA) Small change to export guide
  docs/guides/export.md
  templates/guides/export.md.tmpl
Labels: doc

#1734 NOJIRA: Fix/quality forms
  genesyscloud/quality_forms_evaluation/genesyscloud_quality_forms_evaluation_proxy.go
  genesyscloud/quality_forms_evaluation/resource_genesyscloud_quality_forms_evaluation.go
  genesyscloud/quality_forms_evaluation/resource_genesyscloud_quality_forms_evaluation_schema.go
  genesyscloud/quality_forms_evaluation/resource_genesyscloud_quality_forms_evaluation_test.go
  genesyscloud/quality_forms_evaluation/resource_genesyscloud_quality_forms_evaluation_utils.go
Labels: fix

#1735 Bug/devtooling 1218
  genesyscloud/util/lists/util_lists.go
Labels: bug

#1733 NOJIRA: The Flow LogLevel resource's Exporter never did properly registered
  genesyscloud/flow_loglevel/resource_genesyscloud_flow_loglevel_schema.go
Labels: fix

#1716 NO-JIRA - A few other small fixes found in various resource types while working on DEVTOOLING-1189
  docs/resources/task_management_workitem_schema.md
  genesyscloud/architect_flow/data_source_genesyscloud_flow_test.go
  genesyscloud/architect_flow/resource_genesyscloud_architect_flow_schema.go
  genesyscloud/knowledge_knowledgebase/genesyscloud_knowledge_knowledgebase_proxy.go
  genesyscloud/organization_authentication_settings/resource_genesyscloud_organization_authentication_settings_schema.go
  genesyscloud/routing_language/genesyscloud_routing_language_proxy.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_schema.go
  genesyscloud/task_management_workitem_schema/resource_genesyscloud_task_management_workitem_schema.go
  genesyscloud/task_management_workitem_schema/resource_genesyscloud_task_management_workitem_schema_schema.go
  genesyscloud/task_management_worktype/resource_genesyscloud_task_management_worktype_schema.go
  genesyscloud/user/resource_genesyscloud_user_utils.go
  genesyscloud/webdeployments_configuration/resource_genesyscloud_webdeployments_configuration_schema.go
Labels: fix

#1737 (DEVTOOLING-1227) genesyscloud_knowledge_document_variation: Fix panic conversion error + refactorings
  genesyscloud/knowledge_document/genesyscloud_knowledge_document_proxy.go
  genesyscloud/knowledge_document_variation/resource_genesyscloud_knowledge_document_variation.go
  genesyscloud/knowledge_document_variation/resource_genesyscloud_knowledge_document_variation_utils.go
Labels: fix
