Repository MyPureCloud/terraform-provider-genesyscloud, pull requests merged in 2025-04, with the labels that each got.

#1638 DEVTOOLING-1166: genesyscloud_routing_queue: canned_response_libraries.library_ids TypeList to TypeSet
  docs/resources/routing_queue.md
  genesyscloud/routing_queue/genesyscloud_routing_queue_init_test.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_schema.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_test.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_unit_test.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_utils.go
  genesyscloud/util/test_utils.go
Labels: bug

#1651 DEVTOOLING-1175 - Fix Unaligned Atomic Operations
  genesyscloud/provider/sdk_client_pool.go
Labels: fix

#1654 Feature/devtooling 1020
  docs/data-sources/widget_deployment.md
  docs/resources/widget_deployment.md
  genesyscloud/data_source_genesyscloud_widget_deployment.go
  genesyscloud/data_source_genesyscloud_widget_deployment_test.go
  genesyscloud/dependent_consumers/dependent_consumers.go
  genesyscloud/resource_genesyscloud_init.go
  genesyscloud/resource_genesyscloud_init_test.go
  genesyscloud/resource_genesyscloud_widget_deployment.go
  genesyscloud/resource_genesyscloud_widget_deployment_test.go
  genesyscloud/tfexporter/tf_exporter_resource_test.go
Labels: feature

#1665 Feature DEVTOOLING-1182 Adds a new sanitizer that is dedicated to the needs of BCP
  genesyscloud/resource_exporter/resource_name_sanitizer.go
  genesyscloud/resource_exporter/resource_name_sanitizer_test.go
  genesyscloud/tfexporter/genesyscloud_resource_exporter.go
  genesyscloud/util/feature_toggles/exporter_sanitizer.go
Labels: feature

#1659 Feat/devtooling 1149 - Added team_ids to genesyscloud_recording_media_retention_policy
  docs/resources/recording_media_retention_policy.md
  genesyscloud/recording_media_retention_policy/genesyscloud_recording_media_retention_policy_init_test.go
  genesyscloud/recording_media_retention_policy/resource_genesyscloud_recording_media_retention_policy_schema.go
  genesyscloud/recording_media_retention_policy/resource_genesyscloud_recording_media_retention_policy_test.go
  genesyscloud/recording_media_retention_policy/resource_genesyscloud_recording_media_retention_policy_utils.go
  genesyscloud/team/data_source_genesyscloud_team_test.go
  genesyscloud/team/resource_genesyscloud_team_test.go
  genesyscloud/team/resource_genesyscloud_team_utils.go
Labels: feature

#1588 Feat/devtooling 653 - Implementing whatsapp resource
  docs/data-sources/conversations_messaging_integrations_whatsapp.md
  docs/resources/conversations_messaging_integrations_whatsapp.md
  examples/data-sources/genesyscloud_conversations_messaging_integrations_whatsapp/data-source.tf
  examples/resources/genesyscloud_conversations_messaging_integrations_whatsapp/apis.md
  examples/resources/genesyscloud_conversations_messaging_integrations_whatsapp/resource.tf
  genesyscloud/conversations_messaging_integrations_whatsapp/data_source_genesyscloud_conversations_messaging_integrations_whatsapp.go
  genesyscloud/conversations_messaging_integrations_whatsapp/data_source_genesyscloud_conversations_messaging_integrations_whatsapp_test.go
  genesyscloud/conversations_messaging_integrations_whatsapp/genesyscloud_conversations_messaging_integrations_whatsapp_init_test.go
  genesyscloud/conversations_messaging_integrations_whatsapp/genesyscloud_conversations_messaging_integrations_whatsapp_proxy.go
  genesyscloud/conversations_messaging_integrations_whatsapp/resource_genesyscloud_conversations_messaging_integrations_whatsapp.go
  genesyscloud/conversations_messaging_integrations_whatsapp/resource_genesyscloud_conversations_messaging_integrations_whatsapp_schema.go
  genesyscloud/conversations_messaging_integrations_whatsapp/resource_genesyscloud_conversations_messaging_integrations_whatsapp_test.go
  genesyscloud/conversations_messaging_integrations_whatsapp/resource_genesyscloud_conversations_messaging_integrations_whatsapp_unit_test.go
  genesyscloud/conversations_messaging_integrations_whatsapp/resource_genesyscloud_conversations_messaging_integrations_whatsapp_utils.go
  genesyscloud/provider_registrar/provider_registrar.go
  genesyscloud/tfexporter/tf_exporter_resource_test.go
Labels: feature

#1664 Fixed mistake in knowledge_document resource example
  docs/resources/knowledge_document.md
  examples/resources/genesyscloud_knowledge_document/resource.tf
Labels: doc

#1647 DEVTOOLING-1170 - Ensures there is a retry when updating the queue member's ring
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_members.go
  genesyscloud/routing_queue/resource_genesyscloud_routing_queue_members_test.go
  genesyscloud/util/util_retries.go
Labels: fix

#1669 Feature/devtooling 1183 - Add support to BCP Sanitizer for including a hash of unique fields in the block label
  genesyscloud/architect_flow/resource_genesyscloud_flow.go
  genesyscloud/integration/resource_genesyscloud_integration.go
  genesyscloud/integration_action/resource_genesyscloud_integration_action.go
  genesyscloud/knowledge_document/resource_genesyscloud_knowledge_document.go
  genesyscloud/resource_exporter/resource_exporter.go
  genesyscloud/resource_exporter/resource_name_sanitizer.go
  genesyscloud/resource_exporter/resource_name_sanitizer_test.go
  genesyscloud/responsemanagement_response/resource_genesyscloud_responsemanagement_response.go
  genesyscloud/responsemanagement_responseasset/resource_genesyscloud_responsemanagement_responseasset.go
  genesyscloud/telephony_providers_edges_did_pool/resource_genesyscloud_telephony_providers_edges_did_pool.go
  genesyscloud/tfexporter/genesyscloud_resource_exporter.go
  genesyscloud/user/resource_genesyscloud_user.go
  genesyscloud/util/hash.go
  genesyscloud/util/hash_test.go
Labels: feature

#1677 add directory to flush secret
  docs/resources/oauth_client.md
  genesyscloud/oauth_client/resource_genesyscloud_oauth_client.go
  genesyscloud/oauth_client/resource_genesyscloud_oauth_client_proxy.go
  genesyscloud/oauth_client/resource_genesyscloud_oauth_client_schema.go
  genesyscloud/oauth_client/resource_genesyscloud_oauth_client_utils.go
  genesyscloud/oauth_client/resource_genesyscloude_oauth_client_unit_test.go
  genesyscloud/util/files/util_files.go
Labels: feature

#1678 Fixes DEVTOOLING-1191 - Large Contact Lists not always getting downloaded
  genesyscloud/outbound_contact_list/resource_genesyscloud_outbound_contact_list_utils.go
Labels: fix
